### ISSUE TITLE
Wonder about factor determination

### ISSUE THREAD

**Issue by rgiessmann** [rgiessmann/peaks#7]
When determining the factor numerically, it seems that peaks with a large `peak_height` influence the RMSD value stronger than they should. 

Maybe we should change the RMSD calculation to a relative approach, i.e. calculating deviations in percent points instead of absolute height differences?

**Comment by Ovicula** [comment]
Yes, I guess we should do that.

**Comment by rgiessmann** [comment]
Commit e14bf7afa9fde71d42c6a1d60f068ed270ef31f2 introduced a `relative_mode` option, which fixed this.
